spring.application.name=dataLoader


spring.security.enabled=false


spring.data.mongodb.uri=mongodb+srv://bhanuv584_db_user:67NBXiMHjoFMWSkO@dev-cluster.wlo7hmh.mongodb.net/dev?appName=dev-cluster

server.port=9090

